/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiPublicImageSplatRouteImport } from './routes/api/public/image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageSplatRoute = ApiPublicImageSplatRouteImport.update({
  id: '/api/public/image/$',
  path: '/api/public/image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio/$id': typeof StudioIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/studio/$id'
    | '/work/$slug'
    | '/studio/'
    | '/api/public/image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/studio/$id'
    | '/work/$slug'
    | '/studio'
    | '/api/public/image/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/studio'
    | '/studio/$id'
    | '/work/$slug'
    | '/studio/'
    | '/api/public/image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudioRoute: typeof StudioRouteWithChildren
  WorkSlugRoute: typeof WorkSlugRoute
  ApiPublicImageSplatRoute: typeof ApiPublicImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image/$': {
      id: '/api/public/image/$'
      path: '/api/public/image/$'
      fullPath: '/api/public/image/$'
      preLoaderRoute: typeof ApiPublicImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudioRoute: StudioRouteWithChildren,
  WorkSlugRoute: WorkSlugRoute,
  ApiPublicImageSplatRoute: ApiPublicImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
