/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as StudioExperimentsRouteImport } from './routes/studio.experiments'
import { Route as StudioNavigationRouteImport } from './routes/studio.navigation'
import { Route as StudioToolkitRouteImport } from './routes/studio.toolkit'
import { Route as WebsitesSlugRouteImport } from './routes/websites.$slug'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiPublicImageSplatRouteImport } from './routes/api/public/image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioExperimentsRoute = StudioExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNavigationRoute = StudioNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => StudioRoute,
} as any)
const StudioToolkitRoute = StudioToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => StudioRoute,
} as any)
const WebsitesSlugRoute = WebsitesSlugRouteImport.update({
  id: '/websites/$slug',
  path: '/websites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageSplatRoute = ApiPublicImageSplatRouteImport.update({
  id: '/api/public/image/$',
  path: '/api/public/image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/experiments': typeof StudioExperimentsRoute
  '/studio/navigation': typeof StudioNavigationRoute
  '/studio/toolkit': typeof StudioToolkitRoute
  '/websites/$slug': typeof WebsitesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio/$id': typeof StudioIdRoute
  '/studio/experiments': typeof StudioExperimentsRoute
  '/studio/navigation': typeof StudioNavigationRoute
  '/studio/toolkit': typeof StudioToolkitRoute
  '/websites/$slug': typeof WebsitesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$id': typeof StudioIdRoute
  '/studio/experiments': typeof StudioExperimentsRoute
  '/studio/navigation': typeof StudioNavigationRoute
  '/studio/toolkit': typeof StudioToolkitRoute
  '/websites/$slug': typeof WebsitesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/studio/': typeof StudioIndexRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/studio'
    | '/studio/$id'
    | '/studio/experiments'
    | '/studio/navigation'
    | '/studio/toolkit'
    | '/websites/$slug'
    | '/work/$slug'
    | '/studio/'
    | '/api/public/image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/studio/$id'
    | '/studio/experiments'
    | '/studio/navigation'
    | '/studio/toolkit'
    | '/websites/$slug'
    | '/work/$slug'
    | '/studio'
    | '/api/public/image/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/studio'
    | '/studio/$id'
    | '/studio/experiments'
    | '/studio/navigation'
    | '/studio/toolkit'
    | '/websites/$slug'
    | '/work/$slug'
    | '/studio/'
    | '/api/public/image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  WebsitesSlugRoute: typeof WebsitesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiPublicImageSplatRoute: typeof ApiPublicImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/experiments': {
      id: '/studio/experiments'
      path: '/experiments'
      fullPath: '/studio/experiments'
      preLoaderRoute: typeof StudioExperimentsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/navigation': {
      id: '/studio/navigation'
      path: '/navigation'
      fullPath: '/studio/navigation'
      preLoaderRoute: typeof StudioNavigationRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/toolkit': {
      id: '/studio/toolkit'
      path: '/toolkit'
      fullPath: '/studio/toolkit'
      preLoaderRoute: typeof StudioToolkitRouteImport
      parentRoute: typeof StudioRoute
    }
    '/websites/$slug': {
      id: '/websites/$slug'
      path: '/websites/$slug'
      fullPath: '/websites/$slug'
      preLoaderRoute: typeof WebsitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image/$': {
      id: '/api/public/image/$'
      path: '/api/public/image/$'
      fullPath: '/api/public/image/$'
      preLoaderRoute: typeof ApiPublicImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRoute
  StudioExperimentsRoute: typeof StudioExperimentsRoute
  StudioNavigationRoute: typeof StudioNavigationRoute
  StudioToolkitRoute: typeof StudioToolkitRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRoute,
  StudioExperimentsRoute: StudioExperimentsRoute,
  StudioNavigationRoute: StudioNavigationRoute,
  StudioToolkitRoute: StudioToolkitRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  WebsitesSlugRoute: WebsitesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiPublicImageSplatRoute: ApiPublicImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
